# Generated by Django 3.2.14 on 2022-07-29 22:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_created=True, verbose_name='date-uploaded')),
                ('date_received', models.DateTimeField(blank=True, default=datetime.date.today, null=True, verbose_name='date-received')),
                ('store', models.CharField(blank=True, default='House', max_length=50, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
