# Generated by Django 3.2.14 on 2022-07-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date_uploaded',
            field=models.DateTimeField(auto_now=True, verbose_name='date-uploaded'),
        ),
    ]
