# Generated by Django 3.2.14 on 2022-07-29 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_receipt_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date_received',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date-received'),
        ),
    ]
